# Generated by Django 2.0.8 on 2018-12-26 10:18

import chatrooms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4000)),
                ('raw_data', models.FileField(upload_to=chatrooms.models.generate_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='chatrooms.Room')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
    ]
