# Generated by Django 2.0.8 on 2019-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0006_userinroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_key',
            field=models.TextField(default=''),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['room'], name='chatrooms_p_room_id_78c5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['body_key'], name='chatrooms_p_body_ke_7a5344_idx'),
        ),
    ]
