# Generated by Django 2.0.8 on 2019-05-08 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0007_auto_20190414_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_key', models.TextField(default='')),
                ('body_key_syn', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['type'], name='chatrooms_p_type_f03c0d_idx'),
        ),
        migrations.AddField(
            model_name='chatsyn',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_synonyms', to='chatrooms.Room'),
        ),
        migrations.AddField(
            model_name='chatsyn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_synonyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
