# Generated by Django 2.0.8 on 2019-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0008_auto_20190508_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsyn',
            name='synonym',
            field=models.BooleanField(default=True),
        ),
    ]
